import time
from openai import OpenAI

client = OpenAI()

FILE_IDS = [
"file-5WYMTa6pQv4MKsoSjZDvmA",
"file-HoKtZ6AmbMvCc4iemeXbJi",
"file-HJhpBgcxGhFKMg9uDuMLqG",
"file-Mtcebekr8ZF5Dp5fPFpDuX",
"file-1CWMvg3Kenxxg6nHLJrgJZ",
"file-SDzqhSVEaGP5Dgk8LYxjwY",
"file-LoT8M9fHer8CKahxKBmTn6",
"file-Chwf6YCT7BxmhcdDwrmokQ",
"file-77SLMghZKr8cHD1ZRdawTV",
"file-FYUfPWXmrfcRJg2pctw6Fg",
"file-1hFJ9EjHL53FkzuQR25oxk",
"file-EnpTYNukYp6gMzuPhFRNm3",
"file-1W19MJgyfqSp6HZbBQ4r7U",
"file-Y4hSR9YJR2TBWe9ogqE9vF",
"file-AnTrhSrF336XVx2nu4RZbX",
"file-C4i3WFJy7CDpMhuu3opTSe",
"file-8uvah2Sre9x9dFcmYSfBcR",
"file-64XEDqGpPW5SU283HUGQQT",
"file-DZJtoneVkTYnondtUNbfKX",
"file-JsDBAx5QSR5WUyPrphXrBX",
"file-FUWKV4QScf1N7GbJAzh7aH",
"file-XMXbvdb25YW87dczivMRMQ",
"file-7cj8hoF1Ff7HzqAmiPy3hq",
"file-E32BzPtnZd9h5UTk64Dh4H",
"file-9X8o1bc2DGzYZLA7wQS5DX",
"file-UwS3aaQ9kXxscXKcz6h57H",
"file-SS5jPFAVnLDwreH8QdGxux",
"file-7o1ktDpLb1hVoZZFcFzGq5",
"file-A8Xm1Yd5tXKUTT25mwudZS",
"file-CV1EZn3XUz4UNqVvipquiW",
"file-1JZvZEAi6dFxVgDG2nEEP4",
"file-DEFLiT16a6ucuppjcCKi6b",
"file-Uikz9gxmZFFtm4PbwuzRAk",
"file-CiCfeTixYZxT2xPRrFVb9x",
"file-RVr84MDgmmwhz5HY33t6sc",
"file-Uq5T13MNkVLErdhS6gP96o",
"file-Pu5npEHKWf4ZD3XAJUP7as",
"file-WawBBcHi6GbnE3CMrPqjZz",
"file-4Hm4Xtfr6fvnBgyZ4LboUp",
"file-AVyEULEbEUbLhxJUAtv4MU",
"file-4Nk1ao1v7HMoUjbdK6xs57",
"file-V3boFtrDRRXL6BpjpUER2t",
"file-JFxKvpe9MLMb6hBEUJHwsm",
"file-VQQWhLnjVpa6EJN5iSJyuw",
"file-CUxvoakUNmU2kxGm7wpr4H",
"file-6YbvrS2dBM4oLN8T119aAt",
"file-79zL1Xjvh7B3u1q1HE3Hp1",
"file-YD8muYeFRkhhFX12hBsneT",
"file-G8srbd94WQVae3tCZTDE1u",
"file-WGZjHhFV2XngXnn2gQwWWH",
"file-P2gtZtmtbWmee3hKmqDXjf",
"file-RDSuS4ywprm6eBrAnjYWmo",
"file-EM8BCvJ361d6oJ8qE9YjeU",
"file-JQzW83brvTZf9xY35Fvega",
"file-2p6FC5z2JsJvRiLVoWAarS",
"file-SsFPu15WTA9HdLUqTPWaTS",
"file-WTCzdiTUnLYjmgHtNiUNu1",
"file-PXXTZoQnks3R4hbgVGLXte",
"file-1nzHmAWtJisujhqQ9gJf2u",
"file-VSbwe7s52L1fAjnqBHSsuw",
"file-YQWBRKowKgk5LZTfhe9GaK",
"file-PXaAmpxynF4D5cNTDdgD56",
"file-BqXzmTX5Zxvgea7dHxiY3j",
"file-DM4ozFMwzoGUoAA1HPqB9T",
"file-52D54FPr2hLHgzY4Sbj6Xd",
"file-H9cBP1acq2gYxFy5CfsS8i",
"file-CTz7B4edN8hnJxaAaVn5aB",
"file-SdnwHzTMkuotjJZiyAn8pq",
"file-9aEVHNviQCQ7EVSg7AZPtJ",
"file-D43CdRnRfGUGVYve5NczUY",
"file-XPD6VWQGmXWsRhcBNMhmaV",
"file-PyAvFpaFn7Gzu8ZcEbPqVz",
"file-PE6JmyApHvpkkGC6jGf83y",
"file-RpaCmVm1RoVMdF3BPMuf3z",
"file-XffAURiekhqQUckvWHAEhH",
"file-NeRa2bJRN8EH4nFsR5uvbE",
"file-5vjRv1QEe1FiSUuSQsMSTG",
"file-EeqtkmgZnw6erDRpWiSRMt",
"file-QmxzRsLUJFPJX1CfBABik5",
"file-4PSqFTLpsEYjqw8NVAkSee",
"file-JuS7TZsngNG8UcpBCHfvvp",
"file-C1qc6GfxXPxFq2iJpPnc52",
"file-DzbbzGY5EztfNjTRR3V7Na",
"file-AnvEzQRxGaMr7jvpMF1hKf",
"file-EV8fDGZGe6y1VKXhHoxG36",
"file-JMFJUxTzf5FESPaSSr4z5R",
"file-QAtErJEDVfPv3LiRtAP4pS",
"file-MtW1s2vUDrw4AwHiMJu7WM",
"file-7jVPX58zLTJAeZ88eXnCEs",
"file-NdxSC6e7RUcHp4QX9VLyYY",
"file-67QiXcPuctC457gGHnK1dE",
"file-EXos4CfecYQQMS7jkcN3CS",
"file-Jxw3uM2FzHApvApHrrzzmE",
"file-4EZrGe7RZeBpkJD9wsvFcA",
"file-FcYcm7FhZbwdoXxajhB7ao",
"file-3wrKSFDJhbx4gLahP16eeJ",
"file-YXKht9XKbPwX9s3q8Wxafw",
"file-4jGDJner8oxhf3h5KgddX3",
"file-VkcPcRDsFQxhQrqRA4Jnnm",
"file-12z6E2PwPnUfYut6Y994yQ",
"file-YZJTGxW92Phh3YynhytARS",
"file-23iq2XegExvmSarFpVJvSj",
"file-3WZfpNrNAFdP2mfW1D7JGG",
"file-8QXXiRjPcXjng237DiJLtX",
"file-BouGPoycejSZWMcmYzo3rR",
"file-2UPhPcKgCBJuexP5mvjPF8",
"file-QHk3bKa7e7gmSjSSVFwZ4g",
"file-UwCUKHzntRbxYNCWZRyzLz",
"file-94kFDwbgXKGytdKFNtFS6K",
"file-LwNJRopenWxVPVyY83gzhd",
"file-UkDoFD6eewsHEypE6i5Zsw",
"file-8yhZ1Jd4XvN8fxmGi8ZMt9",
"file-QFoC1HYpf1wqqffzVjCa8X",
"file-DKf5YhAk237CTVMpWMe3EL",
"file-5CQEBcJMNMepyiaH84mxuf",
"file-1Ghxk9zx8YeEh3rjZPWpoS",
"file-XWs1b3mP9hw1Muq5C6fR22",
"file-2WngfSDS4xP9649zggjyAC",
"file-VNJHi9QTDRnAZpAphEU2Xu",
"file-FGYE9oxfEmjc5FrTDCa9EJ",
"file-U6xEFizcSPmxv7bokRLox9",
"file-Jd4pJzJA7RZj58htn9NghF",
"file-H1Gtzib7DQ6VDhdoQG5erH",
"file-MMmcJHgesJdBXmLyjxty9n",
"file-JUUR72XfSy2FBtoksjN6db",
"file-RKMPKk2XF1ZHvehNGpfaAQ",
"file-CFCPGB4R8L5VXyVettpMpN",
"file-HGFED5fUxJMmgz11rEzKns",
"file-TwuxCGSZg7KfStHeHDUwsf",
"file-WdVSc7aV86qTAFetq9f8zf",
"file-G3UkaNrKXkHDF3GbHMyCCw",
"file-Mj3PWjNz78UjS3C8CxK4ny",
"file-X7WoEsMUs9J7WrvQPGVt2k",
"file-VQHTLnQQYsstnDEKrpHahi",
"file-4tF7CL6XeQW3EH5MaS6YXK",
"file-QwE2HvMLiSSZH1kiqhUqYz",
"file-TU4Kmzr5GsCNUtUudhRPpr",
"file-9aEsyoKfSXa92oJEF8Nvjm",
"file-PFnsYM9CUvWWH1XK9dVoyR",
"file-J9jxL2KwgX9Japn1mBPb7o",
"file-5aCrXvobddEnAWxXf8t5W5",
"file-WULVokLftdyVCkqcz37zAQ",
"file-M1qNap6JRvbrAmTEMF8wRu",
"file-CmKLGa4fpcNcA6HUeJtokk",
"file-HRr43yqznqZDGCD7VV19Eu",
"file-RCtLUs4hB7rJc8T1HrXqKf",
"file-CuNY2DEchu5kJK7CE6NXDW",
"file-8ADbh9J3vWSuAVfd3a5Xid",
"file-KN7F75WkVLSzY7mVj28k5p",
"file-FmqMzou2p1dMaFoN41mhro",
"file-5ZgPjkZMYTHN4xRjxTgcr7",
"file-NhrnwzsHwhPbwJjxGqv4pF",
"file-B2JYZnGn9W6KYfrgaKLEcA",
"file-UThfd6znys1okfqg1jQBb7",
"file-1SDMYJ1hgrj2He1tcsNpdz",
"file-D1iVWrHdnZnG3Lntw8XV5h",
"file-NmdoGqd7KFBmxkETSvfFKW",
"file-YE2ChtLSbAno6Kan9Gq1pT",
"file-UJq6s31xxjGyjjhhpQScwM",
"file-526bnT41E6cvzNCzUnPHhL",
"file-5vg1kSSaK3ZqKLoLv6rv66",
"file-PvmtijzDqT4HUgcnfJRRA2",
"file-EVboAxKQwYVEk9PCYGjogg",
"file-DpUrFTFtqgN4EKijHDA32J",
"file-Hy23FQ4dMzTvkT4UpQiVTS",
"file-4WfnJVkWzTtMMskrvWEhfu",
"file-XioJui7366jcWE3HSB36UB",
"file-F8rNbFUyNfqTPm6Mr7b63K",
"file-SzajFXw8TZM66Ce9cm4USg",
"file-KDHafiiQsqdzBFoFbyFeYx",
"file-Qnq7ooFbLbCHZLFUzZQptr",
"file-BRxqGqr2EZq4L4Aah5XdGc",
"file-DoueTivjwwopKBDfmdbcGc",
"file-NZVsHnZ6M7qrxwW2Vr1i96",
"file-DScghVKWeG936ApCDWhPQq",
"file-2RmLGC78sVECAin1Dk7ZoH",
"file-SCM5W1dDFEVhFgeVExs5f8",
"file-TTY7iDy7gt5AoHXhRa8cic",
"file-S46r86qTY9gdYUf2bYgrd6",
"file-XQESo5Ztfrdjy4UWuMLcox",
"file-Ej7i7GM5wPYxt4cMQKZNwB",
    # ... colle ici tous les autres file-XXX que tu as dans les logs
]

VECTOR_STORE_NAME = "hobbes-leviathan-book01"

vs = client.vector_stores.create(name=VECTOR_STORE_NAME)
print("Vector store:", vs.id)

batch = client.vector_stores.file_batches.create(
    vector_store_id=vs.id,
    file_ids=FILE_IDS,
)
print("Batch:", batch.id, "status:", batch.status)

while True:
    b = client.vector_stores.file_batches.retrieve(
    vector_store_id=vs.id,
    batch_id=batch.id,
    )
    print("status:", b.status, "counts:", b.file_counts)
    if b.status in ("completed", "failed", "cancelled"):
        if b.status != "completed":
            raise RuntimeError(f"Indexing ended with status={b.status}")
        break
    time.sleep(2)

print("✅ Ready. vector_store_id =", vs.id)
